# Generated by Django 4.2.10 on 2024-02-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries_to_go', models.CharField(choices=[('MT', 'Malta'), ('UK', 'United Kingdom'), ('FI', 'Finland'), ('DE', 'Germany')], max_length=2)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('external_id', models.IntegerField(null=True, unique=True)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True)),
                ('english_level', models.CharField(blank=True, choices=[('A1', 'A1 Beginner'), ('A2', 'A2 Elementary'), ('B1', 'B1 Intermediate'), ('B2', 'B2 Upper-Intermediate'), ('C1', 'C1 Advanced')], max_length=2, verbose_name='choose your English level')),
                ('bio', models.TextField(blank=True, verbose_name='Why do you want to join our language exchange program?')),
                ('countries_to_go', models.ManyToManyField(blank=True, to='app.country')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
