# Generated by Django 4.2.10 on 2024-02-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_student_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
