# Generated by Django 4.2.10 on 2024-02-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_student_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
