# Generated by Django 4.2.10 on 2024-02-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_student_countries_to_go_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
