# Generated by Django 4.2.10 on 2024-02-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_student_account_number_student_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='card_number',
        ),
    ]
