# Generated by Django 4.2.10 on 2024-02-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_student_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tralala',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
