# Generated by Django 4.2.10 on 2024-03-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_card_client_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
        migrations.AddField(
            model_name='client',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
