# Generated by Django 4.2.10 on 2024-03-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_account_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
    ]
