# Generated by Django 4.2.10 on 2024-03-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_account_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
