# Generated by Django 4.2.10 on 2024-03-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_client_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bio',
        ),
    ]
